# Generated by Django 3.1.1 on 2020-09-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=100, unique=True, verbose_name='笔记标题')),
                ('context', models.TextField(default='', verbose_name='笔记内容')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
